name: diffmat
channels:
  - pytorch
  - defaults
dependencies:
  - imageio>=2.9.0
  - numpy>=1.21.5
  - pandas>=1.3.5
  - pip>=21.2.4
  - python>=3.7
  - pytorch=1.11.0
  - pyyaml>=6.0
  - scipy>=1.7.3
  - setuptools>=61.2.0
  - torchvision=0.12.0
